### ISSUE TITLE
Initial Todo's

### ISSUE THREAD

**Issue by semperos** [semperos/screwdriver#2]
## Bugs/Brittleness
- [x] <del>Files *.coffee get copied to output by the filesystem watching functionality</del>
- [ ] During JS compilation, we ignore Dust files and vice versa (task is to determine if there is better way to architect this)
- [ ] Expose config to allow _not_ wrapping Dust files in AMD/define block.
- [ ] Remove requirement that all 5 possible asset folders be present.
- [ ] Proper way to include Screwdriver as a Maven dependency (e.g., it shouldn't be shipped with a WAR that gets built)
## Running External Tools
- [ ] Allow running arbitrary executables at different build phases (e.g., for browserify builds)
## Jetty
- [ ] Support for authentication (e.g., SSO func.)
## LiveReload
- [ ] Configure Jetty with push func.
- [ ] Include client-side implementation to match
## SPDY
- [ ] SPDY support
- [ ] Websockets over SPDY
## Other Asset Languages
- [ ] Stylus
- [ ] Document how to add new languages (what methods to impl., how to add it to asset pipeline workflow (build vs. watch), etc.)
## Multi-threading
- [ ] Multi-thread Rhino (queues of files to read/write)
## Config Interface
- [ ] Amount of Mavenization to incorporate (e.g., make Screwdriver a Mojo)?
- [ ] Passing arguments vs. Minimal Config
- [ ] Languages?

Try minimal config first, see how it grows/feels/leeches
## Optimization
- [x] RequireJS (using Google Closure, code & concept review)
- [ ] CSS (YuiCompressor)
- [ ] Images (discussion)
## Research: Async I/O
- [ ] Research use of async I/O for file reads/writes
- [ ] Do early performance comparison to see if net gains are worth the complexity
